apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp 
        image: chegehmark/beka_web:latest
        ports:
        - containerPort: 5000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: USERNAME
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: PASSWORD
        - name: HOST
          value: "postgres-service"
        - name: DB_NAME
          value: "postgres"   # or "pastry_db" if that’s what you actually want
